[로그인] 애플 로그인 연동
team-dayeng/Dayeng pull request #57
Opened 2023-02-22 16:20 UTC by sangyeon3

## 작업 내용:

### ASAuthorizationControllerProxy 구현 
-> apple login을 RxSwift로 처리

```swift
ASAuthorizationAppleIDProvider().rx.login(...).subscribe(....)
```

### 애플 로그인 구현

첫 로그인| 이미 연동된 경우 | 로그인 실패시 alert
-----|-----|-----
로그인 후 메인 화면 | 스플래시 후 바로 메인 | 
![RPReplay_Final1677082080](https://user-images.githubusercontent.com/68235938/220685476-7e2bc19b-6691-4af7-95a8-a11e9979e0fe.gif) | ![RPReplay_Final1677082344](https://user-images.githubusercontent.com/68235938/220687732-74068c72-a1b3-4279-8f72-464e2fed4fe6.gif) |  ![RPReplay_Final1677082515](https://user-images.githubusercontent.com/68235938/220687749-a027b4b8-9396-4f1c-b33b-c83397b9f4f4.gif)

로그인시 흐름은 다음과 같습니다
```
(로그인뷰컨) 애플 로그인 버튼 클릭 - (로그인 뷰모델) 애플 로그인 - (유저케이스+유저레포) 파베 로그인 
- (로그인 뷰모델) UserDefaults에 uid 저장 + DayengDefaults에 유저 정보(User, Answers) 저장
```

이때, 다음과 같이 UserDefaults에 2개의 id를 저장하게 되는데,
i) `appleID`는 애플 로그인 연동 여부를 확인할 때 사용합니다
ii) `uid`는 firebase auth에서의 uid로, firestore에 user가 저장될 때 해당 uid로 문서가 저장됩니다.
아마 여러분은 uid만 사용하실 거 같지만 알아두면 좋을 것 같아 말씀드립니다!

```swift
UserDefaults.standard.set(appleIDCredential.user, forKey: "appleID")
UserDefaults.standard.set(user.uid, forKey: "uid")
```

그리고 forKey의 rawString은 디벨롭 따오면 승기님이 만드신 UserDefaults Extension의 DayengKeys에 정의하여 변경하겠습니다!

## 질문:

- 로그인하는 동안 인디케이터 뷰 추후 추가하겠습니다!

### 확인 사항:
- [x] 양심적인 PR양을 준수하였습니다.

2023-02-22 16:35 UTC, seungki-cho commented
# 질문
왜 뷰모델에 애플로그인이 있나요?

2023-02-22 16:44 UTC, sangyeon3 commented
> # 질문
> 왜 뷰모델에 애플로그인이 있나요?

엇 ㄹㅔ포에 있어야 하나요? 아니면 서비스를 해야할까요?

2023-02-22 17:01 UTC, seungki-cho commented
> ㄹㅔ포에 있어야 하나요? 아니면 서비스를 해야

싸비스가 맞지 않을까요 ?

2023-02-22 17:20 UTC, seungki-cho requested changes
수고하셨습니다! 많은 걸 하셨네요 하지만 뷰모델 이슈로 기각

2023-02-22 17:20 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +    private func randomNonceString(length: Int = 32) -> String {
# 의견 

아래와 같은 코드는 어떠신가요 ?? 

```swift
private func newRandomNonceString(length: Int = 32) -> String {
    precondition(length > 0)
    let charset: [Character] = Array("0123456789ABCDEFGHIJKLMNOPQRSTUVXYZabcdefghijklmnopqrstuvwxyz-._")
    
    var randoms = [UInt8](repeating: 0, count: length)
    let errorCode = SecRandomCopyBytes(kSecRandomDefault, randoms.count, &randoms)
    if errorCode != errSecSuccess {
        fatalError(
            "Unable to generate nonce. SecRandomCopyBytes failed with OSStatus \(errorCode)"
        )
    }
        
    return String(randoms.map { random in
        charset[Int(random)%charset.count]
    })
}
```

SecRandomCopyBytes 자체가 암호학적으로 안전한 난수고,
UInt8로 생성한다면 2^8 이라, ```charset.count == 64```로 나눠져, 모듈로 연산을 해도 난수성을 유지합니다.

계산이 틀렸을까봐 코드로도 확인했는데 맞는 것 같습니다.
(new 붙은게 위 코드입니다.)
<img width="1120" alt="스크린샷 2023-02-23 오전 2 17 10" src="https://user-images.githubusercontent.com/57134892/220705504-dd7b1cdf-f73f-409c-87e5-7b7137ad0c12.png">

2023-02-23 07:28 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Domain/UseCase/Auth/DefaultLoginUseCase.swift
> +            print("sign out error: \(error)")
알럿을 띄우는 방식으로 할까요? 오류메세지와 함께

2023-02-23 16:27 UTC, sangyeon3 commented on Dayeng/Dayeng/App/SceneDelegate.swift
>                  print("Apple ID 사용 중단")
ㅎㅎ 반영 완~

2023-02-23 16:27 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Auth/DefaultLoginUseCase.swift
> +            print("sign out error: \(error)")
넵 alert으로 수정하게씃ㅂ니다 ~

2023-02-23 16:32 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Auth/DefaultLoginUseCase.swift
> +            print("sign out error: \(error)")
이 부분이 애플과 파베 auth 로그인 후에 firestore에 새로운 user를 업로드하는 과정에서 오류가 생기면 파베 auth sign out 하는거라 
유저 업로드 과정에서 오류 생겼을 때 이미 "로그인에 실패했습니다" alert을 띄워줘서,
또 "로그아웃 실패" 라는 알럿을 띄우기에는 이상한 거 같은데 어떻게들 생각하시나요 ???
좋은 방안 있으면 말씀해주시면 반영하겠습니다!

2023-02-23 16:45 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +        input.appleLoginButtonDidTap.subscribe(onNext: { [weak self] in
수정했습니다 감사합니다

2023-02-23 16:45 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +                        // TODO: 만약 애플 로그인 - 로그아웃 후 재로그인 한다면 ?? 즉, 퀘스쳔 데이터가 있는 상태라면 ??
이 부분 관련하여 피알 수정했습니다! 보고 의견 주시면 감사하겠습니다 ~~

2023-02-23 16:53 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +            }
수정했습니다 감사합니다 ~~

2023-02-23 17:56 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +    private func randomNonceString(length: Int = 32) -> String {
역시 암호학 학사
수정해씁니다 감사합니다 ㅎㅎ

2023-02-23 19:17 UTC, seungki-cho commented on Dayeng/Dayeng/App/Coordinator/AppCoordinator.swift
> +            .subscribe(onNext: { [weak self] result in
왜 as driver 대신에 observeOn을 하셨나요?

2023-02-24 04:56 UTC, NamSeok-Bae commented on Dayeng/Dayeng/ASAuthorizationControllerProxy.swift
> +@available(iOS 13.0, *)
저희 앱 타겟이 13이상부터 될텐데 이거 필요없지않나요?

2023-02-24 05:04 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Domain/UseCase/Auth/DefaultLoginUseCase.swift
> +            print("sign out error: \(error)")
인정합니다. output으로 알럿 띄워주니깐 따로 필요가 없을 것 같습니다.

2023-02-24 05:07 UTC, NamSeok-Bae requested changes

2023-02-24 05:07 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Presentation/Splash/SplashViewModel.swift
> +
딥링크 -> 로그인 -> 메인으로 진행될 때 고려하면 self.useCase.fetchQuestions()가 따로 진행되야할 거 같습니다. 이러면 코드가 중복될거같습니다.

2023-02-24 17:13 UTC, sangyeon3 commented on Dayeng/Dayeng/App/Coordinator/AppCoordinator.swift
> +            .subscribe(onNext: { [weak self] result in
에러 처리가 필요했는데 driver는 에러를 받지 못해서 입니다!

2023-02-24 17:13 UTC, sangyeon3 commented on Dayeng/Dayeng/ASAuthorizationControllerProxy.swift
> +@available(iOS 13.0, *)
앱 타겟 확정인가여 ?

2023-02-24 17:14 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Splash/SplashViewModel.swift
> +
넵 수정했습니다

2023-02-25 01:00 UTC, NamSeok-Bae commented on Dayeng/Dayeng/ASAuthorizationControllerProxy.swift
> +@available(iOS 13.0, *)
DayengAlertVC에서 addAction이 iOS14 버전이긴한데, Diffable이랑 compositional 있으니 iOS13 이상으로 하는거 어떠세요? 전 솔직히 앱 버전 좀 많이 높혀도 괜찮다고 생각합니다.

``` swift

func setRightButtonAction(handler: (() -> Void)? = nil) {
        rightButton.addAction(
            UIAction(handler: { _ in handler?() }),
            for: .touchUpInside
        )
        buttonStackView.addArrangedSubview(rightButton)
    }
    
    func setLeftButtonAction(handler: (() -> Void)? = nil) {
        leftButton.addAction(
            UIAction(handler: { _ in handler?() }),
            for: .touchUpInside
        )
        buttonStackView.addArrangedSubview(leftButton)
    }

```

2023-02-25 02:57 UTC, NamSeok-Bae approved these changes

2023-02-25 09:09 UTC, seungki-cho approved these changes
수고하셨습니다! 
혹시 스크린샷은 제 계정 해킹한건가요? 아니면 개명하신건가요??

2023-02-25 09:09 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +            .disposed(by: disposeBag)
좋습니다

2023-02-25 09:09 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +            .disposed(by: disposeBag)
## 질문
하지만 Presentation Layer (ViewModel)에   
로그인 결과에 따라 데이터를 저장하는
애플로그인 성공하면 파이어베이스 로그인하는
등의 코드가 있어도 될까요?

2023-02-25 09:17 UTC, sangyeon3 commented on Dayeng/Dayeng/Util/Extension/UserDefaults+.swift
> +        set { standard.set(newValue, forKey: DayengKeys.userName) }
오키 ~

2023-02-25 09:54 UTC, sangyeon3 commented on Dayeng/Dayeng/Util/Service/AppleLoginService.swift
> +                        (familyName! + givenName!) : UserDefaults.userName else {
수정!

2023-02-25 17:07 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
> +            .disposed(by: disposeBag)
수정해스빈다 찐 마지막 리뷰 부탁드리미다

2023-02-25 17:28 UTC, seungki-cho approved these changes
수고하셨습니다 👍  💯

2023-02-25 17:28 UTC, seungki-cho commented on Dayeng/Dayeng/Util/Extension/UserDefaults+.swift
> +            }
ㅎㅎ 👍

2023-02-25 17:28 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
>      // MARK: - Output
```
import AuthenticationServices
import CryptoKit
import FirebaseAuth
```
필요한가요?

2023-02-25 17:31 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Auth/LoginViewModel.swift
>      // MARK: - Output
아이코 감사요 👍

2023-02-26 03:46 UTC, merged