[로그인] 카카오 로그인 연동
team-dayeng/Dayeng pull request #58
Opened 2023-02-26 10:31 UTC by sangyeon3

## 작업 내용:

### 카카오 로그인 서비스 구현

```swift
protocol KakaoLoginService {
    func isAvailable() -> Bool
    func autoSignIn() -> Observable<Void>
    func signIn() -> Observable<(email: String, password: String, userName: String)>
    func signOut() -> Completable
    func unlink() -> Completable
}
```

(자동로그인에 필요할까해서 isAvailable()과 autoSignIn() 구현해놨는데 안 필요해서 현재 위 두 함수는 미사용 중입니다 !
혹시 나중에 필요할까봐 냅뒀습니다)

### 카카오 로그인 구현 & 로그인 하는 동안 Indicator 뷰 표시

카카오톡이 설치되어 있는 경우 어플을 통해 로그인| 카카오톡 없는 경우 웹을 통해 카카오 계정 로그인 | 승인하지 않고 껐을 때 alert
-----|-----|-----
![RPReplay_Final1677406690](https://user-images.githubusercontent.com/68235938/221404900-b8498528-0dfe-410a-9cec-827e65959f90.gif) | ![RPReplay_Final1677406788](https://user-images.githubusercontent.com/68235938/221404903-047b0df3-225f-4ce4-b71a-d279ec8e7c4a.gif) |  ![RPReplay_Final1677406734](https://user-images.githubusercontent.com/68235938/221404907-c13ab94b-af00-4ab8-8d2a-0f86b739b8a3.gif)

### 자동로그인

- 스플래시 화면에서 `Auth.auth().currentUser != nil` 이면 메인 화면으로 넘어가도록 해놨습니다

## 질문:

- 자동 로그인 할 때 `Auth.auth().currentUser != nil` 조건만 확인하고 넘어가도 될까요?
아니면 사용자가 전에 애플로그인을 했다면 스플래시에서 다시 애플 로그인(ex. 토큰 재인증 같은 로직)을 하고 넘어가야 할까요?

### 확인 사항:
- [x] 양심적인 PR양을 준수하였습니다.

closes #4

2023-02-28 05:39 UTC, seungki-cho requested changes
## 답변
> 자동 로그인 할 때 Auth.auth().currentUser != nil 조건만 확인하고 넘어가도 될까요?
아니면 사용자가 전에 애플로그인을 했다면 스플래시에서 다시 애플 로그인(ex. 토큰 재인증 같은 로직)을 하고 넘어가야 할까요?

지금 애플은 연결 끊으면 ```credentialRevokedNotification```로 알 수 있지만,
카카오로그인은 연결 해제를 해도 앱이 계속됩니다.
![카카오끊기](https://user-images.githubusercontent.com/57134892/221759868-139da994-b3af-4766-aa8b-e6e0e0ce19bf.jpeg)


다음과 같은 코드로 연결을 끊고 스플래시에서 확인해보니
```
 UserApi.shared.accessTokenInfo(completion: {
    (tokenInfo, error) in
    if let error = error {
        print(error)
    }
    else {
        print(tokenInfo)
    }
    
})
```
다음과 같이 에러가 뜹니다.
```
Optional(KakaoSDKCommon.SdkError.AuthFailed(reason: KakaoSDKCommon.AuthFailureReason.InvalidGrant, errorInfo: Optional(KakaoSDKCommon.AuthErrorInfo(error: KakaoSDKCommon.AuthFailureReason.InvalidGrant, errorDescription: Optional("expired_or_invalid_refresh_token")))))
```

화이팅입니다!

## 질문
- 어떤 방법으로 로그인을 했는지 확인할 수 있나요?

2023-02-28 05:39 UTC, seungki-cho commented on Dayeng/Dayeng/App/SceneDelegate.swift
> +    }
카카오 SDK 좋네요 ㄷ ㄷ

2023-02-28 05:39 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/Auth/DefaultLoginUseCase.swift
> +                                .bind(to: observer)
```bind to observer``` 첨보네요 굳

2023-02-28 05:39 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/DefaultSplashUseCase.swift
> -        }
살려내!!!!

2023-02-28 05:39 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Auth/LoginViewController.swift
> +                self.showIndicator()
인디케이터가 있으니까 UX에 좋네요

2023-02-28 05:39 UTC, seungki-cho commented on Dayeng/Dayeng/Util/Service/DefaultKakaoLoginService.swift
> +                        .disposed(by: owner.disposeBag)
```withUnretained``` 들은
```guard let self else { return }``` 에서 return 대신 적을 게 없어서 작성 하신거겠죠 ?

2023-03-01 05:43 UTC, sangyeon3 commented on Dayeng/Dayeng/Util/Service/DefaultKakaoLoginService.swift
> +                        .disposed(by: owner.disposeBag)
넵 맞아요

2023-03-01 05:43 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/DefaultSplashUseCase.swift
> -        }
오키 ~

2023-03-01 06:48 UTC, sangyeon3 commented
@seungki-cho 

### 질문
어떤 방법으로 로그인을 했는지 확인할 수 있나요?

### 답변

1. `Auth.auth().currentUser != nil` 이면 애플 또는 카카오 둘 중 하나로 로그인되어있음
2. `if self.kakaoLoginService.isAvailableAutoSignIn()` 을 통해 카카오 로그인 여부 확인
3. 카카오 로그인이 아니라면 애플 로그인이므로 `self.appleLoginService.autoSignIn()` 수행

자세한 로직은 아래 코드 참고해주세요

```swift
    func tryAutoLogin() -> Observable<Bool> {
        Observable.create { [weak self] observer in
            guard let self,
                  Auth.auth().currentUser != nil else {
                observer.onNext(false)
                return Disposables.create()
            }
            
            if self.kakaoLoginService.isAvailableAutoSignIn() {
                self.kakaoLoginService.autoSignIn()
                    .do(onNext: { result in
                        if !result { try? Auth.auth().signOut() }
                    })
                    .bind(to: observer)
                    .disposed(by: self.disposeBag)
            } else {
                self.appleLoginService.autoSignIn()
                    .do(onNext: { result in
                        if !result { try? Auth.auth().signOut() }
                    })
                    .bind(to: observer)
                    .disposed(by: self.disposeBag)
            }
            
            return Disposables.create()
        }
    }
```

2023-03-01 06:56 UTC, NamSeok-Bae approved these changes
## 질문
설정 창에서 Logout 할때도 Auth.auth().signOut 을 통해 진행되는걸까요?

2023-03-01 06:56 UTC, NamSeok-Bae commented on Dayeng/Dayeng/App/AppDelegate.swift
> +
## 질문
appKey는 어디서 불어온거에요?

2023-03-01 06:56 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Util/Service/DefaultKakaoLoginService.swift
> +                        .disposed(by: owner.disposeBag)
이런 방법도 있었군요 신기하네요.

2023-03-01 06:57 UTC, sangyeon3 commented on Dayeng/Dayeng/App/AppDelegate.swift
> +
카카오 developer에 저희 앱 등록하고 받은 키입니다!

2023-03-01 06:58 UTC, sangyeon3 commented
@NamSeok-Bae 

### 질문
설정 창에서 Logout 할때도 Auth.auth().signOut 을 통해 진행되는걸까요?

### 답변
맞습니다 ~~

2023-03-01 07:13 UTC, NamSeok-Bae commented on Dayeng/Dayeng/App/AppDelegate.swift
> +
감사합니다.

2023-03-02 05:32 UTC, seungki-cho approved these changes
수고하셨습니다!

근데 apple 처럼 카카오도 중간에 연결 끊어도 로그인으로 가는 처리 안 해도 될까요?

2023-03-04 09:01 UTC, merged