[설정] 로그아웃, 회원 탈퇴 (Firebase Auth + Kakao)
team-dayeng/Dayeng pull request #60
Opened 2023-03-05 05:54 UTC by sangyeon3

## 작업 내용:

### 로그아웃 + 회원 탈퇴

- 로그아웃/탈퇴 후 로그인 화면으로 전환합니다.
- 로그아웃/탈퇴에 실패할 경우, alert 창을 띄워줍니다.

로그아웃| 회원 탈퇴
-----|-----
![RPReplay_Final1677995343](https://user-images.githubusercontent.com/68235938/222943975-a96c55b4-7abc-46e0-b3e5-ee785d399ba8.gif) | ![RPReplay_Final1677995361](https://user-images.githubusercontent.com/68235938/222943966-9f852206-7e23-428b-8992-3b7d2a9ac687.gif)

## 질문:

- alert에서 "확인" 클릭시 딜레이 없이 로그아웃/탈퇴되어 로그인 화면으로 가긴 하던데 그래도 인디케이터 넣어야 할까요?

## 참고:

- 애플 로그아웃/탈퇴(revoke)는 api 요청 해야해서 아직입니다!
https://developer.apple.com/documentation/sign_in_with_apple/revoke_tokens

### 확인 사항:
- [x] 양심적인 PR양을 준수하였습니다.

2023-03-05 14:45 UTC, NamSeok-Bae approved these changes
고생하셨습니다!

2023-03-05 14:45 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Presentation/Coordinator/MainCoordinator.swift
> +}
👍

2023-03-06 09:35 UTC, seungki-cho requested changes
수고하셨습니다!
느린 인터넷 환경에서도 빠르게 로그아웃/탈퇴가 될까요 ?  인디케이터를 추가해야겠네요!

![Simulator Screen Recording - iPhone 14 Pro - 2023-03-06 at 18 33 20](https://user-images.githubusercontent.com/57134892/223071534-e008cc6e-fa1a-49c5-bba9-0443c8781b80.gif)

- 테스트 환경 
<img width="653" alt="스크린샷 2023-03-06 오후 6 34 42" src="https://user-images.githubusercontent.com/57134892/223071772-65ea42d1-4acd-427b-afc8-a8e58fd84e4c.png">


- 사용법 
[블로그 링크](https://m.blog.naver.com/rumble82/221575821051)

2023-03-10 07:41 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Setting/DefaultSettingUseCase.swift
> +import FirebaseAuth
아무래도 그렇죠 ?? ㅎㅎ 다음 피알에 만들어서 올리겠습니다!

2023-03-10 07:41 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Setting/DefaultSettingUseCase.swift
> +                        observer.onCompleted()
넵 맞습니다!

2023-03-10 07:41 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Setting/DefaultSettingUseCase.swift
> +            guard let self else { return Disposables.create() }
추가하겠슴니다 ~~

2023-03-10 07:43 UTC, sangyeon3 commented
> 수고하셨습니다! 느린 인터넷 환경에서도 빠르게 로그아웃/탈퇴가 될까요 ? 인디케이터를 추가해야겠네요!
> 
> * 테스트 환경
> 
> <img alt="스크린샷 2023-03-06 오후 6 34 42" width="653" src="https://user-images.githubusercontent.com/57134892/223071772-65ea42d1-4acd-427b-afc8-a8e58fd84e4c.png">
> 
> * 사용법
>   [블로그 링크](https://m.blog.naver.com/rumble82/221575821051)

우와 감사합니다 추가하겠습니다! 굿

2023-03-11 10:50 UTC, seungki-cho approved these changes
👍

2023-03-12 07:31 UTC, merged