[메인] 글작성, 수정, 바인딩
team-dayeng/Dayeng pull request #65
Opened 2023-04-03 08:35 UTC by seungki-cho

### 작업내용
- UserRepository - 답변 수정
    ```swift
    func editAnswer(answer: String, index: Int) -> Observable<Void>
    ```
- MainViewController - CollectionView Binding Rx로 변경
    ```swift
    output.questionsAnswers
        .bind(to: collectionView.rx.items(cellIdentifier: MainCell.identifier, cellType: MainCell.self)
        ) { [weak self] (index, questionAnswer, cell) in
            // 바인딩
        }
    ```
    - Rx의 ```bind(to: collectionView.rx.items(cellIdentifier:, cellType:)```를 사용하기 위해서, Question과 Answer를 하나의 배열 (튜플로 묶은)로 보냈습니다.
        - 셀을 꺼내는 작업을 하는 코드라서,
        - 두 개의 데이터를 바인딩할 수 없어서 하나로 합쳤습니다.
- MainViewController - 셀 ( 답변하기 )터치 구현
    ```swift
    private let editButtonDidTapped = PublishSubject<Int>()
    var editButtonDisposables = [Int: Disposable]()

    // willDisplay
    editButtonDisposables[indexPath.row] = cell.mainView.editButtonDidTapped
            .map { indexPath.row }
            .bind(to: editButtonDidTapped)

    // didEndDisplaying
    editButtonDisposables[indexPath.row]?.dispose()
        editButtonDisposables.removeValue(forKey: indexPath.row)
    ```
    - 셀의 특수성 ( 화면에 안 보이면 사라짐 )으로 모든 셀을 그냥 구독할 경우 셀 재생성 과정에서 오류가 발생해서 위와 같은 코드로 작성했습니다.
    - willDisplay
        - 셀 - mainview - editButtonDidTapped을 인덱스 패스(인덱스)와 바인드
        - editButtonDisposables에 인덱스에 맞게 Disposable 저장
    - didEndDisplaying
        - 없어지는 셀의 인덱스의 Disposables을 dispose
- 새로고침 + 셀 가리기
    - 마지막 셀 일 경우 새로고침 버튼이 보입니다.
        - 근데 UIBarButtonItem의 isHidden 을 수정하는 건 16.0부터라 tintColor + isEnabled 로 구현했습니다.
    - 유즈케이스에서 마지막 셀을 가리라고 할 경우 가립니다.

### 기획 + 질문

- 새로고침과 셀 가리기가 로직을 모르겠습니다.
    - Input
        - 답변 한 경우 / 안 한 경우
        - 새로고침 받은 경우 / 안 받은 경우
        - 새로고침 답변을 한 경우 / 안 한 경우
    - Output
        - 셀 가리기 여부
        - 새로고침 가능 여부
    
    기존 기획은  
    답변하기 어려운 경우 -> 새로고침 가능  
    이미 답변한 경우 -> 가리기  
    인데 오늘의 답변은 무조건 새로고침 하는게 하나 더 보니까 좋은 거 아닌가요?? 블러랑 겹치는게 아닌가요 ??

    - 알잘딱깔센 하게 하려 했는데 센스 부족으로 실패했습니다.
    - 여려분들의 도움이 필요해요.

2023-04-03 16:11 UTC, sangyeon3 approved these changes
수고하셨습니다~

2023-04-03 16:11 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Main/MainViewController.swift
> +            .bind(to: editButtonDidTapped)
구읏 아이디어 조으네요

2023-04-03 23:53 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Presentation/Main/MainCell.swift
> +            $0.left.right.equalToSuperview().inset(15)
leading 은 text가 시작하는 방향, left는 뷰의 왼쪽 인데 아랍권?에 경우엔 오른쪽부터 읽어서 leading이 오른쪽이랍니다.

left, right 같은 경우 leading , trailing으로 다 맞추는거 어떤가요?

2023-04-06 05:31 UTC, NamSeok-Bae reviewed
작성페이지에서 에러가 났을 경우 알럿을 띄워지고 확인을 눌렀을 때 indicator가 삭제되질 않습니다.

2023-04-06 05:42 UTC, NamSeok-Bae reviewed
메인 화면에서 드래그로 다음 질문으로 넘어가야되는데 드래그가 안되네요

2023-04-06 05:42 UTC, NamSeok-Bae commented on Dayeng/Dayeng/Util/Extension/UserDefaults+.swift
> +    }
이것들은 언제 쓰는걸까요?

2023-04-06 05:54 UTC, NamSeok-Bae requested changes
고생하셨습니다!

2023-04-06 07:40 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/DefaultMainEditUseCase.swift
> +        Observable.of(DayengDefaults.shared.questions[index])
하나의 요소만 전달하니까 Just가 맞겠네요 감샇ㅂ니다

2023-04-06 07:42 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/DefaultMainUseCase.swift
> +        }
감사합니다 ㅎㅎ

2023-04-06 07:42 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Common/CommonMainView.swift
> +    }
감사합니다 ㅎㅎ

2023-04-06 07:42 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Main/MainCell.swift
> +            $0.left.right.equalToSuperview().inset(15)
저만 저래놨네요 죄송합니다 ㅎㅎ
바꿨습니다!

2023-04-06 07:42 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Main/MainViewController.swift
> +            .bind(to: editButtonDidTapped)
감사합니다 ㅎㅎ

2023-04-06 07:46 UTC, seungki-cho commented on Dayeng/Dayeng/Data/Repository/DefaultUserRepository.swift
>          }
good

2023-04-06 07:46 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/Entity/User.swift
> +    var bonusQuestionDate: Date?
yes

2023-04-06 09:22 UTC, sangyeon3 approved these changes
수고하셨습니다

2023-04-06 09:22 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/DefaultMainUseCase.swift
> +        let startIndex = isAnswered ? user.currentIndex : (user.currentIndex + 1)
굿

2023-04-06 09:22 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Main/MainViewController.swift
> +                }
initialPath 값이 존재할 때 처음 한번만 initialPath에 해당하는 셀 보여주고 그 뒤에 스크롤해서 보여지는 셀은 해당 코드로 가지 않는 것 맞나요?

2023-04-06 09:22 UTC, sangyeon3 commented on Dayeng/Dayeng/Util/Extension/Date+.swift
> +
안쓰시나요??

2023-04-06 09:23 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Main/MainViewController.swift
> +                }
Yes, that's correct. The initial cell corresponding to the initialPath value will only be shown once initially, and the subsequent cells that are shown as the user scrolls will not execute that code.

2023-04-06 09:25 UTC, seungki-cho commented on Dayeng/Dayeng/Util/Extension/Date+.swift
> +
outdated

2023-04-06 09:27 UTC, sangyeon3 commented on Dayeng/Dayeng/Util/Extension/Date+.swift
> +
remove 부탁

2023-04-06 10:13 UTC, NamSeok-Bae approved these changes

2023-04-11 07:21 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Main/DefaultMainUseCase.swift
> +                }, self?.getBlurStartingIndex())
glse??

2023-04-11 07:21 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Main/MainViewModel.swift
> +                    .debug()
debug!

2023-04-11 07:21 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Main/MainViewModel.swift
> +                        self.cannotFindUserError.onNext(())
fetchData에서 에러가 나면 cannotFIndUSerError인가요?

2023-04-11 12:32 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/Main/DefaultMainUseCase.swift
> +                }, self?.getBlurStartingIndex())
nil보내면 돼서 넘어갈라했는데 들켰네요

2023-04-11 16:50 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Main/MainViewModel.swift
> +                    .debug()
tank you

2023-04-11 16:51 UTC, merged