[메인] 블러 처리 화면 광고 보기 뷰
team-dayeng/Dayeng pull request #81
Opened 2023-05-07 11:16 UTC by NamSeok-Bae

### 작업 내용
- 메인 셀에 '광고 보기 뷰' 추가
- 메인 뷰에서 RxGesture 추가하여 메인 셀에 adsContentView 클릭 구독
- 광고 보기 눌렀을 때 답변안한 질문이 있는지 체크함.
- 모든 질문을 답했다면 광고 보기 가능.
- 광고 보면 currentIndex + 1 을 해서 Firebase에 올려줍니다.

2023-05-07 11:32 UTC, seungki-cho requested changes
빌드가 안 돼요

2023-05-07 11:32 UTC, seungki-cho commented on Dayeng/Dayeng/Presentation/Main/ViewController/MainViewController.swift
> +                    if let rewardedAd {
self가 없어서 빌드가 안 됩니다

2023-05-07 12:19 UTC, sangyeon3 commented on Dayeng/Dayeng.xcodeproj/project.pbxproj
> +				E54F3E892A0687CE003B35CF /* FirebaseAnalytics in Frameworks */,
이것도 광고에 필요한건가요?

2023-05-07 12:19 UTC, sangyeon3 commented on Dayeng/Dayeng/Data/Repository/DefaultUserRepository.swift
> +        if user.answers.count < user.currentIndex {
이거 무슨로직인가요?

2023-05-07 12:24 UTC, NamSeok-Bae commented on Dayeng/Dayeng.xcodeproj/project.pbxproj
> +				E54F3E892A0687CE003B35CF /* FirebaseAnalytics in Frameworks */,
google admob과 firebase analytics가 연동이 되기에 해줬습니다.

2023-05-07 18:23 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Main/ViewController/MainViewController.swift
> +                } else {
```swift
    private func setupAds() {
        GADRewardedAd.load(withAdUnitID: "ca-app-pub-3402143822000520/5224075704",
                           request: GADRequest()) { (ads, error) in
          if let error = error {
            print("Rewarded ad failed to load with error: \(error.localizedDescription)")
            return
          }
          print("Loading Succeeded")
          self.rewardedAd = ads
          self.rewardedAd?.fullScreenContentDelegate = self
        }
    }
```

setupAds()에서 error가 있으면 rewardedAd가 nil이 되는데, 
setupAds() 혹은 output.adsViewTapResult을 구독한 부분에서 rewardedAd가 nil이 되는 경우에 대한 예외처리가 필요할 것 같습니다

2023-05-07 18:23 UTC, sangyeon3 commented on Dayeng/Dayeng/Presentation/Main/ViewController/MainViewController.swift
> +                }
adsContentView의 탭제스쳐를 구독하는 부분을 
190~197 lines의 output.questionsAnswers을 콜렉션뷰 아이템에 바인딩 하는 부분에서 
여기로 수정하면 어떨까요? 광고 셀 하나에서만 구독하면 좋을 것 같습니다

```swift
                if indexPath.row == blurIndex {
                    cell.adsContentView.rx.tapGesture()
                        .when(.recognized)
                        .subscribe(onNext: { [weak self] _ in
                            guard let self else { return }
                            self.adsViewDidTapped.accept(())
                        })
                        .disposed(by: cell.disposeBag)
                    
                    cell.setupAds()
                }
```

2023-05-07 18:24 UTC, seungki-cho approved these changes
수고하셨습니다!

2023-05-07 18:24 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/Main/DefaultMainUseCase.swift
> +    }
```suggestion
func isAvailableWatchAds() -> Observable<Bool> {
        guard let user = DayengDefaults.shared.user else { return Observable.just(false) }
        let today = Date().convertToString(format: "yyyy.MM.dd.E")
        let isAnswered = user.answers.last?.date == today
        let isAvailable = !user.answers.isEmpty && isAnswered && user.answers.count == user.currentIndex
        
        return Observable.just(isAvailable)
    }
```

2023-05-07 18:29 UTC, sangyeon3 commented on Dayeng/Dayeng/Data/Repository/DefaultUserRepository.swift
> +        }
아래랑 많이 비슷한데 메소드화 하면 어떨가요!

2023-05-07 18:31 UTC, seungki-cho commented on Dayeng/Dayeng/Domain/UseCase/Main/DefaultMainEditUseCase.swift
> +            }
광고봄 = user.answers.count < user.currentIndex
광고 본 거면 index + 1 이 오늘 거
안 본 거면 index가 오늘 거
라서 그런게 아닐까요?

2023-05-07 18:36 UTC, sangyeon3 commented on Dayeng/Dayeng/Domain/UseCase/Main/DefaultMainEditUseCase.swift
> +            }
아 이해됐습니다 감사합니다

그렇다면

### 의견 

```swift
        let isWatchedAd = user.answers.count < user.currentIndex
        if (isWatchedAd && user.currentIndex == index + 1) || user.currentIndex == index {
            return userRepository.uploadAnswer(answer: answer)
        }
```

2023-05-08 03:27 UTC, sangyeon3 approved these changes

2023-05-08 03:35 UTC, merged